<div class="manager-actions">
    <a class="manager-action" href="<?php echo esc_url(zigurat_inventory_page_url('inventory-list')); ?>"><span class="manager-action__icon" aria-hidden="true">📦</span><strong>انبارداری</strong><small>ورود مستقیم به بخش کامل انبارداری</small></a>
    <a class="manager-action" href="<?php echo esc_url(zigurat_invoice_page_url()); ?>"><span class="manager-action__icon" aria-hidden="true">🧾</span><strong>بخش فاکتور</strong><small>ثبت، اصلاح، فهرست و چاپ فاکتورها</small></a>
    <a class="manager-action" href="<?php echo esc_url(add_query_arg('manager-section', 'views', zigurat_manager_login_url())); ?>"><span class="manager-action__icon" aria-hidden="true">📈</span><strong>آمار بازدید سایت</strong><small>نمایش عددی و نموداری بازدید مطالب و پروژه‌ها</small></a>
    <a class="manager-action" href="<?php echo esc_url(add_query_arg('manager-section', 'pricing', zigurat_manager_login_url())); ?>"><span class="manager-action__icon" aria-hidden="true">🧮</span><strong>محاسبه قیمت</strong><small>محاسبه قیمت محصولات بر اساس ابعاد، هزینه‌ها و درصد سود</small></a>
    <div class="manager-action manager-action--inactive" aria-label="گزارش حساب؛ در آینده طراحی می‌شود"><span class="manager-action__icon" aria-hidden="true">📊</span><strong>گزارش حساب</strong><small>این بخش بعداً برای گزارش‌های مالی طراحی می‌شود</small></div>
    <?php $unread_applications = function_exists('zigurat_application_unread_count') ? zigurat_application_unread_count() : 0; ?>
    <a class="manager-action manager-action--applications<?php echo $unread_applications ? ' has-notification' : ''; ?>" href="<?php echo esc_url(add_query_arg('manager-section', 'applications', home_url('/login/'))); ?>"><?php if ($unread_applications): ?><b class="manager-action__badge"><?php echo esc_html(number_format_i18n($unread_applications)); ?> جدید</b><?php endif; ?><span class="manager-action__icon" aria-hidden="true">🤝</span><strong>درخواست‌های همکاری</strong><small>مشاهده همکاران و تأمین‌کنندگان ثبت‌نام‌شده</small></a>
</div>
